### ISSUE TITLE
Collector crashes due to custom timezone configured on Clickhouse server

### ISSUE THREAD

**Issue by AlexeiZenin** [SigNoz/opentelemetry-collector-contrib#2025]
**Describe the bug**
When running a clickhouse cluster with the America/New_York timezone configured the collector crashes with this error message:
```
Error: cannot build exporters: error creating clickhousetraces exporter: error connecting to primary db: could not load time location: unknown time zone America/New_York
2022/07/20 18:14:42 collector server run finished with error: cannot build exporters: error creating clickhousetraces exporter: error connecting to primary db: could not load time location: unknown time zone America/New_York
```

It seems the otel-collector has no time zone data included in its binary or within the docker image.

**Steps to reproduce**

1. Configure a clickhouse server with the America/New_York timezone or any other timezone.
1. Run the collector against the clickhouse cluster and it should exit in error (crash).

**What did you expect to see?**
The collector should not crash and support whatever timezone is set on the server.

**What did you see instead?**
Indefinite crashing of the collector; unusable

**What version did you use?**
Version: signoz/otelcontribcol:0.45.1-1.1

Extended above image with this dockerfile:
```docker
FROM signoz/otelcontribcol:0.45.1-1.1
COPY otel-collector-config.yaml /etc/otel/config.yaml
```

**What config did you use?**
Config:
```yml
receivers:
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: localhost:12345
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    send_batch_size: 10000
    send_batch_max_size: 11000
    timeout: 10s
  signozspanmetrics/prometheus:
    metrics_exporter: prometheus
    latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 50ms, 100ms, 250ms, 500ms, 1000ms, 1400ms, 2000ms, 5s, 10s, 20s, 40s, 60s ]
    dimensions_cache_size: 10000

exporters:
  clickhousetraces:
    datasource: tcp://${CLICKHOUSE_HOST}:${CLICKHOUSE_PORT}/?database=signoz_traces&username=${CLICKHOUSE_USER}&password=${CLICKHOUSE_PWD}
  clickhousemetricswrite:
    endpoint: tcp://${CLICKHOUSE_HOST}:${CLICKHOUSE_PORT}/?database=signoz_metrics&username=${CLICKHOUSE_USER}&password=${CLICKHOUSE_PWD}
    resource_to_telemetry_conversion:
      enabled: true
  prometheus:
    endpoint: 0.0.0.0:8889

extensions:
  health_check:
    endpoint: 127.0.0.1:13133
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [signozspanmetrics/prometheus, batch]
      exporters: [clickhousetraces]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhousemetricswrite]
    metrics/spanmetrics:
      receivers: [otlp/spanmetrics]
      exporters: [prometheus]

```

**Environment**
OS: Ran in it in Docker on my Mac

**Additional context**
I fixed the issue using this dockerfile which downloaded TZ data and baked it into the image (inspired by this SO [post](https://stackoverflow.com/questions/59094236/error-unknown-time-zone-america-los-angeles-in-time-loadlocation)):
```
FROM alpine:3.15.5 as build
ADD https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip /zoneinfo.zip
RUN chmod 777 /zoneinfo.zip

FROM signoz/otelcontribcol:0.45.1-1.1
ENV ZONEINFO /zoneinfo.zip
COPY --from=build /zoneinfo.zip /zoneinfo.zip
COPY otel-collector-config.yaml /etc/otel/config.yaml
```
Collector booted up without exception after this fix.

With Go 1.15 you can also embed this into the binary instead of installing into the docker image: https://go.dev/doc/go1.15#time/tzdata

Either approach will work I believe (I only tested the dockerfile approach).

Slack Signoz thread: https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1658340994426549
